config/routes.rb
ChettiarMess::Application.routes.draw do
  resources :ushas

  match 'uploads', to: 'upload#index', via: [:get,:post]
  match 'uploadfile', to: 'upload#uploadFile', via: [:get,:post]

end

app/models/usha.rb
class Usha < ActiveRecord::Base
  attr_accessible :category, :explanation, :recipe, :title, :food_type, :video
end

app/models/videofile.rb
class Videofile < ActiveRecord::Base
  # attr_accessible :title, :body
  def self.save(upload)
  	directory = "public/data"
  	file_name = upload['datafile'].original_filename
  	path = File.join(directory, file_name)
  	File.open(path, 'wb') { |f| f.write(upload['datafile'].read) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController

	def index
		render :index
	end

	def uploadFile
		post = Videofile.save(params[:upload])
		render :text => "File has been saved successfully"
	end
end

app/controllers/ushas_controller.rb
class UshasController < ApplicationController
  # GET /ushas
  # GET /ushas.json
  def index
    @ushas = Usha.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ushas }
    end
  end

  # GET /ushas/1
  # GET /ushas/1.json
  def show
    @usha = Usha.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usha }
    end
  end

  # GET /ushas/new
  # GET /ushas/new.json
  def new
    @usha = Usha.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usha }
    end
  end

  # GET /ushas/1/edit
  def edit
    @usha = Usha.find(params[:id])
  end

  # POST /ushas
  # POST /ushas.json
  def create
    @usha = Usha.new(params[:usha])

    respond_to do |format|
      if @usha.save
        format.html { redirect_to @usha, notice: 'Usha was successfully created.' }
        format.json { render json: @usha, status: :created, location: @usha }
      else
        format.html { render action: "new" }
        format.json { render json: @usha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ushas/1
  # PUT /ushas/1.json
  def update
    @usha = Usha.find(params[:id])

    respond_to do |format|
      if @usha.update_attributes(params[:usha])
        format.html { redirect_to @usha, notice: 'Usha was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ushas/1
  # DELETE /ushas/1.json
  def destroy
    @usha = Usha.find(params[:id])
    @usha.destroy

    respond_to do |format|
      format.html { redirect_to ushas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ushas_helper.rb
module UshasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChettiarMess</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
 <script>
   videojs.options.flash.swf = "video-js.swf";
 </script>

<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/upload/index.html.erb
<h1>upload a file </h1>

<%= form_tag(uploadfile_path,:method => 'post', :multipart => true) do %>
	<p> <label for="Upload file">Select file </label>:
		<%= file_field 'upload','datafile' %>
		<%= submit_tag 'upload' %>
<% end %>

app/views/ushas/_form.html.erb
<%= form_for(@usha) do |f| %>
  <% if @usha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usha.errors.count, "error") %> prohibited this usha from being saved:</h2>

      <ul>
      <% @usha.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :food_type %><br />
    <%= f.text_field :food_type %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :recipe %><br />
    <%= f.text_area :recipe %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br />
    <%= f.text_area :explanation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ushas/edit.html.erb
<h1>Editing usha</h1>

<%= render 'form' %>

<%= link_to 'Show', @usha %> |
<%= link_to 'Back', ushas_path %>

app/views/ushas/index.html.erb
<h1>Listing ushas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>FoodType</th>
    <th>Category</th>
    <th>Video</th>
    <th>Recipe</th>
    <th>Explanation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ushas.each do |usha| %>
  <tr>
    <td><%= usha.title %></td>
    <td><%= usha.food_type %></td>
    <td><%= usha.category %></td>
    <td><%= usha.video %></td>
    <td><%= usha.recipe %></td>
    <td><%= usha.explanation %></td>
    <td><%= link_to 'Show', usha %></td>
    <td><%= link_to 'Edit', edit_usha_path(usha) %></td>
    <td><%= link_to 'Destroy', usha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usha', new_usha_path %>

app/views/ushas/new.html.erb
<h1>New usha</h1>

<%= render 'form' %>

<%= link_to 'Back', ushas_path %>

app/views/ushas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @usha.title %>
</p>

<p>
  <b>Food Type:</b>
  <%= @usha.food_type %>
</p>

<p>
  <b>Category:</b>
  <%= @usha.category %>
</p>

<p>
  <b>Video:</b>
  <%= @usha.video %>
</p>
<%= video_tag("movie.mp4",poster:"rails.png" , :size => "720x640",:controls => true,:autobuffer => true) %>


<p>
  <b>Recipe:</b>
  <%= @usha.recipe %>
</p>

<p>
  <b>Explanation:</b>
  <%= @usha.explanation %>
</p>


<%= link_to 'Edit', edit_usha_path(@usha) %> |
<%= link_to 'Back', ushas_path %>